/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Roy
 */

#include <bits/stdc++.h>

using namespace std;

class CoinCombinationsII {
public:
    void solve(std::istream &in, std::ostream &out) {
    }
};

int main() {
    CoinCombinationsII solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
